baseURL: http://example.org/
languageCode: en-us
title: Timer | Responsive Multipurpose Bootstrap Hugo Template
theme: timer-hugo
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Service
      url: service
      weight: 3
    - name: Gallery
      url: gallery
      weight: 4
    - name: Blog
      url: blog
      weight: 5
    - name: Contact
      url: contact
      weight: 6
params:
  about:
    content: Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia.
      I hold a master degree of Web Design from the World University.And scrambled
      it to make a type specimen book. It has survived not only five centuries. <br>
      <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci
      voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda
      iusto reiciendis placeat. Temporibus, vero.
    enable: yes
    image: images/about/about.jpg
    title: ABOUT ME
  author: Themefisher
  banner:
    bgImage: images/slider.jpg
    btn: yes
    btnText: Download More
    btnURL: https://themefisher.com/
    description: WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL
      DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY
      WORK.
    enable: yes
    flipText:
      - title: DESIGNER
      - title: DEVELOPER
      - title: FATHER
    heading: HI, MY NAME IS JONATHON & I AM A
  contactFormAction: '#'
  cta:
    btnText: Contact with me
    btnURL: /contact
    content: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus
      commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium.
    enable: yes
    title: SO WHAT YOU THINK ?
  dateFormat: 6 January 2006
  description: Airspace Hugo theme
  googleAnalitycsID: Your ID
  home: Home
  logo: images/logo.png
  portfolio:
    enable: yes
    subtitle: Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor
      neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat,
      nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus.
    title: Latest Works
  socialIcon:
    - icon: ion-social-facebook
      url: '#'
    - icon: ion-social-instagram
      url: '#'
    - icon: ion-social-linkedin
      url: '#'
