baseURL: https://examplesite.com
languageCode: en-us
title: Liva | Personal blog template
theme: liva-hugo
summaryLength: '10'
paginate: 6
disqusShortname: ''
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  author: Themefisher
  cookies:
    enable: yes
    expire_days: 2
  copyright: '| copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights
    Reserved |'
  description: This is meta description
  email: demo@email.com
  googleAnalitycsID: Your ID
  home: Home
  location: Dhaka, Bangladedsh
  logo: images/logo.png
  mobile: 0124857985320
  newsletter:
    content: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
      eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
      At vero
    enable: yes
    title: Join Our Newsletter
  plugins:
    css:
      - URL: plugins/bootstrap/bootstrap.min.css
      - URL: plugins/slick/slick.css
      - URL: plugins/themify-icons/themify-icons.css
      - URL: plugins/venobox/venobox.css
    js:
      - URL: plugins/jQuery/jquery.min.js
      - URL: plugins/bootstrap/bootstrap.min.js
      - URL: plugins/slick/slick.min.js
      - URL: plugins/venobox/venobox.min.js
      - URL: plugins/search/fuse.min.js
      - URL: plugins/search/mark.js
      - URL: plugins/search/search.js
  preloader:
    enable: yes
    preloader: ''
  search:
    enable: yes
  social:
    - icon: ti-facebook
      link: '#'
      title: facebook
    - icon: ti-twitter-alt
      link: '#'
      title: twitter
    - icon: ti-instagram
      link: '#'
      title: instagram
    - icon: ti-github
      link: '#'
      title: github
    - icon: ti-linkedin
      link: '#'
      title: linkedin
menu:
  footer:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Post
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Post
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
